# Generated by Django 5.1.6 on 2025-02-27 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rental",
            name="rental_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="rental",
            name="return_date",
            field=models.DateField(),
        ),
    ]
