# Generated by Django 5.1.6 on 2025-02-27 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0002_alter_rental_rental_date_alter_rental_return_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="available",
        ),
    ]
