# Generated by Django 5.1.6 on 2025-03-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0003_remove_car_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="image",
            field=models.ImageField(
                default="car_images/default.jpg", upload_to="car_images/"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="car",
            name="license_plate",
            field=models.CharField(default="AA123AB", max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
