# Generated by Django 5.1.6 on 2025-03-07 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0004_car_image_car_license_plate"),
    ]

    operations = [
        migrations.AddField(
            model_name="rental",
            name="is_cancelled",
            field=models.BooleanField(default=False),
        ),
    ]
